# This is a basic workflow to help you get started with Actions

name: SFDX Code Scanner

# Controls when the workflow will run
on:
  # Triggers the workflow on push events, but not for the master branch
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch

# A workflow run is made up of one or more "jobs" that can run sequentially or in parallel
jobs:
  document-lwc:
    # The type of "runner" (virtual machine) that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Use appirios DX Docker image, so we have NodeJS, Java, DX, etc... pre-installed 
      - uses: docker://appirio/dx

      # Checkout the curren branch to get access to the repo
      - name: Checking out Source code
        uses: actions/checkout@v1

      # Generate LWC documentation
      - name: Generating LWC Documentation
        run: |
          # Install JSDoc
          npm install -g jsdoc

          # Run JSDoc
          jsdoc force-app/main/default/lwc/component/component.js
      
      # Upload Documents if the previous job was successful
      - name: Uploding LWC Documentation
        uses: actions/upload-artifact@v2.2.4
        if: success()
        with:
          name: LWC Docs
          path: out/*
          
      - name: Upload Documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "out/"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
